### ISSUE TITLE
virus

### ISSUE THREAD

**Issue by ghost** [Rosalie241/PJ64Launcher#2]
https://www.virustotal.com/gui/file/84011aaed59fbf575a3003476c20e3173e4c35205994b4a3228550d195b1fa4e
https://www.virustotal.com/gui/file/8f3e73ddd53e931521fdf9d38d184b1daeb5ab4dff5cee328b9be11d928cea09

**Comment by Rosalie241** [comment]
this application is opensource, you can view the code and compile it yourself if you don't trust it.
anti-virus often give a false positive which I can do nothing about so please don't spread lies.
